[2024-03-29T16:23:49.331-0300] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dados-combustivel.load_minio_to_bucket manual__2024-03-29T19:20:45.089075+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-03-29T16:25:06.707-0300] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dados-combustivel.load_minio_to_bucket manual__2024-03-29T19:20:45.089075+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
