[2024-03-24T05:15:06.190-0300] {processor.py:161} INFO - Started process (PID=15936) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:15:06.190-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:15:06.191-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:15:06.191-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:15:06.194-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:15:06.193-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:15:06.194-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:15:06.194-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:15:06.194-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:15:06.202-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2024-03-24T05:16:00.890-0300] {processor.py:161} INFO - Started process (PID=16430) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:16:00.900-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:16:00.902-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:16:00.901-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:16:00.906-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:16:00.905-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:16:00.907-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:16:00.906-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:16:00.907-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:16:00.919-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-03-24T05:16:57.131-0300] {processor.py:161} INFO - Started process (PID=16935) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:16:57.132-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:16:57.133-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:16:57.133-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:16:57.137-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:16:57.136-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:16:57.137-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:16:57.137-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:16:57.138-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:16:57.146-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-03-24T05:17:50.900-0300] {processor.py:161} INFO - Started process (PID=17429) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:17:50.902-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:17:50.903-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:17:50.902-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:17:50.906-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:17:50.905-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:17:50.906-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:17:50.906-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:17:50.906-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:17:50.916-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-03-24T05:18:42.070-0300] {processor.py:161} INFO - Started process (PID=17902) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:18:42.071-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:18:42.072-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:18:42.072-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:18:42.076-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:18:42.076-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:18:42.077-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:18:42.076-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:18:42.077-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:18:42.086-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-03-24T05:19:33.955-0300] {processor.py:161} INFO - Started process (PID=18564) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:19:33.957-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:19:33.958-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:19:33.958-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:19:33.963-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:19:33.962-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:19:33.964-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:19:33.963-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:19:33.964-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:19:33.974-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-24T05:20:23.845-0300] {processor.py:161} INFO - Started process (PID=19020) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:20:23.848-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:20:23.849-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:20:23.848-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:20:23.851-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:20:23.850-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:20:23.851-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:20:23.851-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:20:23.851-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:20:23.859-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-03-24T05:21:11.267-0300] {processor.py:161} INFO - Started process (PID=19549) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:21:11.269-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:21:11.270-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:21:11.270-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:21:11.273-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:21:11.273-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:21:11.274-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:21:11.274-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:21:11.274-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:21:11.287-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-03-24T05:22:02.320-0300] {processor.py:161} INFO - Started process (PID=20014) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:22:02.321-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:22:02.322-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:22:02.322-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:22:02.325-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:22:02.324-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:22:02.325-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:22:02.325-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:22:02.325-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:22:02.335-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-03-24T05:22:55.421-0300] {processor.py:161} INFO - Started process (PID=20499) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:22:55.422-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:22:55.423-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:22:55.423-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:22:55.426-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:22:55.426-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:22:55.427-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:22:55.427-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:22:55.427-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:22:55.436-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-03-24T05:23:46.839-0300] {processor.py:161} INFO - Started process (PID=20961) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:23:46.841-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:23:46.842-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:23:46.842-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:23:46.847-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:23:46.846-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:23:46.847-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:23:46.847-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:23:46.847-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:23:46.855-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-03-24T05:24:38.245-0300] {processor.py:161} INFO - Started process (PID=21492) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:24:38.247-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:24:38.248-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:24:38.247-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:24:38.251-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:24:38.250-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:24:38.251-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:24:38.251-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:24:38.251-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:24:38.260-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-03-24T05:25:30.999-0300] {processor.py:161} INFO - Started process (PID=21978) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:25:31.005-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:25:31.006-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:25:31.006-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:25:31.009-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:25:31.008-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:25:31.009-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:25:31.009-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:25:31.009-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:25:31.019-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-24T05:26:28.258-0300] {processor.py:161} INFO - Started process (PID=22491) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:26:28.259-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:26:28.260-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:26:28.260-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:26:28.262-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:26:28.262-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:26:28.262-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:26:28.262-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:26:28.263-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:26:28.271-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-03-24T05:27:27.158-0300] {processor.py:161} INFO - Started process (PID=23018) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:27:27.160-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:27:27.161-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:27:27.161-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:27:27.166-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:27:27.165-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:27:27.166-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:27:27.166-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:27:27.166-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:27:27.177-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-24T05:28:18.852-0300] {processor.py:161} INFO - Started process (PID=23455) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:28:18.853-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:28:18.854-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:28:18.853-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:28:18.857-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:28:18.856-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:28:18.857-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:28:18.857-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:28:18.858-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:28:18.866-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-03-24T05:29:14.744-0300] {processor.py:161} INFO - Started process (PID=23932) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:29:14.746-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:29:14.747-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:29:14.746-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:29:14.749-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:29:14.749-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:29:14.749-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:29:14.749-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:29:14.749-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:29:14.757-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-03-24T05:30:01.713-0300] {processor.py:161} INFO - Started process (PID=24437) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:30:01.714-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:30:01.715-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:30:01.715-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:30:01.717-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:30:01.717-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:30:01.718-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:30:01.718-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:30:01.718-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:30:01.726-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-03-24T05:30:54.855-0300] {processor.py:161} INFO - Started process (PID=24919) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:30:54.857-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:30:54.858-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:30:54.858-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:30:54.860-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:30:54.860-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:30:54.861-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:30:54.861-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:30:54.861-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:30:54.870-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-03-24T05:31:49.916-0300] {processor.py:161} INFO - Started process (PID=25422) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:31:49.918-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:31:49.919-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:31:49.919-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:31:49.922-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:31:49.922-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:31:49.922-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:31:49.922-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:31:49.923-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:31:49.931-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-03-24T05:32:43.541-0300] {processor.py:161} INFO - Started process (PID=25904) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:32:43.542-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:32:43.543-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:32:43.543-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:32:43.545-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:32:43.545-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:32:43.546-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:32:43.545-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:32:43.546-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:32:43.555-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-03-24T05:33:34.000-0300] {processor.py:161} INFO - Started process (PID=26372) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:33:34.001-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:33:34.002-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:33:34.002-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:33:34.005-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:33:34.004-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:33:34.005-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:33:34.005-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:33:34.005-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:33:34.015-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-03-24T05:34:21.611-0300] {processor.py:161} INFO - Started process (PID=26816) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:34:21.612-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:34:21.613-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:34:21.612-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:34:21.615-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:34:21.615-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:34:21.616-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:34:21.615-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:34:21.616-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:34:21.627-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-03-24T05:35:11.752-0300] {processor.py:161} INFO - Started process (PID=27277) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:35:11.754-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:35:11.755-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:35:11.755-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:35:11.759-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:35:11.758-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:35:11.759-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:35:11.759-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:35:11.759-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:35:11.773-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-24T05:36:07.442-0300] {processor.py:161} INFO - Started process (PID=27775) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:36:07.444-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:36:07.445-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:36:07.444-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:36:07.448-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:36:07.447-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:36:07.449-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:36:07.448-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:36:07.449-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:36:07.459-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-03-24T05:36:59.315-0300] {processor.py:161} INFO - Started process (PID=28251) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:36:59.317-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:36:59.318-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:36:59.318-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:36:59.320-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:36:59.320-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:36:59.321-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:36:59.321-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:36:59.321-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:36:59.329-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-03-24T05:37:51.757-0300] {processor.py:161} INFO - Started process (PID=28740) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:37:51.758-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:37:51.759-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:37:51.759-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:37:51.762-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:37:51.761-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:37:51.762-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:37:51.762-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:37:51.762-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:37:51.771-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-03-24T05:38:46.539-0300] {processor.py:161} INFO - Started process (PID=29438) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:38:46.541-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:38:46.542-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:38:46.542-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:38:46.544-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:38:46.544-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:38:46.545-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:38:46.545-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:38:46.545-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:38:46.553-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-03-24T05:39:45.218-0300] {processor.py:161} INFO - Started process (PID=30030) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:39:45.224-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:39:45.225-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:39:45.224-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:39:45.229-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:39:45.229-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:39:45.230-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:39:45.229-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:39:45.230-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:39:45.239-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-03-24T05:40:38.578-0300] {processor.py:161} INFO - Started process (PID=30515) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:40:38.579-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:40:38.581-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:40:38.580-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:40:38.584-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:40:38.584-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:40:38.584-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:40:38.584-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:40:38.584-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:40:38.594-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-03-24T05:41:33.970-0300] {processor.py:161} INFO - Started process (PID=31010) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:41:33.972-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:41:33.974-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:41:33.973-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:41:33.980-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:41:33.979-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:41:33.982-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:41:33.981-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:41:33.982-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:41:34.002-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-03-24T05:42:26.215-0300] {processor.py:161} INFO - Started process (PID=31492) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:42:26.217-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:42:26.218-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:42:26.217-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:42:26.221-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:42:26.221-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:42:26.222-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:42:26.222-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:42:26.222-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:42:26.231-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-03-24T05:43:20.499-0300] {processor.py:161} INFO - Started process (PID=31986) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:43:20.501-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:43:20.502-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:43:20.501-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:43:20.504-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:43:20.504-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:43:20.505-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:43:20.505-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:43:20.506-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:43:20.515-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-03-24T05:44:14.038-0300] {processor.py:161} INFO - Started process (PID=32410) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:44:14.039-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:44:14.040-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:44:14.040-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:44:14.045-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:44:14.044-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:44:14.045-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:44:14.045-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:44:14.045-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:44:14.057-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-24T05:45:01.564-0300] {processor.py:161} INFO - Started process (PID=32916) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:45:01.565-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:45:01.566-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:45:01.566-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:45:01.570-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:45:01.569-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:45:01.570-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:45:01.570-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:45:01.570-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:45:01.584-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-03-24T05:45:51.469-0300] {processor.py:161} INFO - Started process (PID=33377) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:45:51.470-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:45:51.471-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:45:51.471-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:45:51.474-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:45:51.474-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:45:51.475-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:45:51.475-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:45:51.475-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:45:51.487-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-03-24T05:46:44.779-0300] {processor.py:161} INFO - Started process (PID=33863) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:46:44.781-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:46:44.782-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:46:44.781-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:46:44.785-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:46:44.785-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:46:44.786-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:46:44.785-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:46:44.786-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:46:44.795-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-03-24T05:47:38.734-0300] {processor.py:161} INFO - Started process (PID=34368) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:47:38.736-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:47:38.737-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:47:38.737-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:47:38.740-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:47:38.739-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:47:38.740-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:47:38.740-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:47:38.740-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:47:38.748-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-03-24T05:48:31.994-0300] {processor.py:161} INFO - Started process (PID=34852) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:48:31.995-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:48:31.996-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:48:31.996-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:48:31.999-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:48:31.998-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:48:31.999-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:48:31.999-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:48:31.999-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:48:32.010-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-03-24T05:49:23.568-0300] {processor.py:161} INFO - Started process (PID=35351) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:49:23.569-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:49:23.570-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:49:23.570-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:49:23.573-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:49:23.572-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:49:23.573-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:49:23.573-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:49:23.573-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:49:23.581-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2024-03-24T05:50:15.084-0300] {processor.py:161} INFO - Started process (PID=35798) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:50:15.086-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:50:15.087-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:50:15.087-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:50:15.092-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:50:15.091-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:50:15.092-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:50:15.092-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:50:15.092-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:50:15.101-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-24T05:51:04.416-0300] {processor.py:161} INFO - Started process (PID=36256) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:51:04.418-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:51:04.419-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:51:04.418-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:51:04.424-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:51:04.423-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:51:04.424-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:51:04.424-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:51:04.425-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:51:04.434-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-03-24T05:51:55.749-0300] {processor.py:161} INFO - Started process (PID=36722) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:51:55.751-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:51:55.752-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:51:55.752-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:51:55.755-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:51:55.755-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:51:55.756-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:51:55.756-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:51:55.756-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:51:55.766-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-03-24T05:52:48.631-0300] {processor.py:161} INFO - Started process (PID=37208) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:52:48.633-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:52:48.633-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:52:48.633-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:52:48.636-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:52:48.636-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:52:48.637-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:52:48.637-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:52:48.637-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:52:48.646-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2024-03-24T05:53:38.158-0300] {processor.py:161} INFO - Started process (PID=37664) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:53:38.160-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:53:38.161-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:53:38.161-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:53:38.164-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:53:38.164-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:53:38.164-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:53:38.164-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:53:38.165-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:53:38.173-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-03-24T05:54:30.976-0300] {processor.py:161} INFO - Started process (PID=38202) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:54:30.979-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:54:30.980-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:54:30.979-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:54:30.982-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:54:30.982-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:54:30.982-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:54:30.982-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:54:30.983-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:54:30.992-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-03-24T05:55:12.325-0300] {processor.py:161} INFO - Started process (PID=38928) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:55:12.328-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:55:12.330-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:55:12.330-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:55:12.333-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:55:12.333-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:55:12.334-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:55:12.334-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:55:12.334-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:55:12.370-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-03-24T05:55:43.341-0300] {processor.py:161} INFO - Started process (PID=39438) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:55:43.343-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:55:43.344-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:55:43.344-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:55:43.348-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:55:43.348-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:55:43.349-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:55:43.349-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:55:43.349-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:55:43.377-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-24T05:56:13.459-0300] {processor.py:161} INFO - Started process (PID=39804) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:56:13.460-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:56:13.461-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:56:13.461-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:56:13.463-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:56:13.463-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:56:13.464-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:56:13.464-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:56:13.464-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:56:13.489-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-03-24T05:56:43.926-0300] {processor.py:161} INFO - Started process (PID=40120) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:56:43.927-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:56:43.928-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:56:43.927-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:56:43.930-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:56:43.929-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:56:43.930-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:56:43.930-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:56:43.930-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:56:43.955-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-03-24T05:57:14.766-0300] {processor.py:161} INFO - Started process (PID=40494) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:57:14.767-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:57:14.768-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:57:14.767-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:57:14.770-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:57:14.770-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:57:14.771-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:57:14.771-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:57:14.771-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:57:14.795-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-03-24T05:57:45.130-0300] {processor.py:161} INFO - Started process (PID=40803) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:57:45.130-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:57:45.131-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:57:45.131-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:57:45.134-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:57:45.134-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:57:45.135-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:57:45.135-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:57:45.135-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:57:45.164-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-24T05:58:16.137-0300] {processor.py:161} INFO - Started process (PID=41179) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:58:16.138-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:58:16.138-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:58:16.138-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:58:16.141-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:58:16.140-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:58:16.141-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:58:16.141-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:58:16.141-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:58:16.165-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-03-24T05:58:47.241-0300] {processor.py:161} INFO - Started process (PID=41494) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:58:47.242-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:58:47.243-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:58:47.242-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:58:47.245-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:58:47.245-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:58:47.246-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:58:47.246-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:58:47.246-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:58:47.271-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-03-24T05:59:18.095-0300] {processor.py:161} INFO - Started process (PID=41868) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:59:18.096-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:59:18.096-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:59:18.096-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:59:18.099-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:59:18.098-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:59:18.099-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:59:18.099-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:59:18.099-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:59:18.124-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-03-24T05:59:49.191-0300] {processor.py:161} INFO - Started process (PID=42182) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:59:49.193-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T05:59:49.194-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:59:49.194-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:59:49.197-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:59:49.197-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T05:59:49.198-0300] {logging_mixin.py:188} INFO - [2024-03-24T05:59:49.197-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T05:59:49.198-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T05:59:49.227-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-03-24T06:00:19.495-0300] {processor.py:161} INFO - Started process (PID=42610) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:00:19.496-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:00:19.497-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:00:19.497-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:00:19.500-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:00:19.499-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:00:19.500-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:00:19.500-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:00:19.500-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:00:19.525-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-03-24T06:00:51.275-0300] {processor.py:161} INFO - Started process (PID=42933) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:00:51.277-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:00:51.278-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:00:51.278-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:00:51.282-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:00:51.281-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:00:51.282-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:00:51.282-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:00:51.283-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:00:51.311-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-03-24T06:01:21.580-0300] {processor.py:161} INFO - Started process (PID=43296) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:01:21.581-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:01:21.583-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:01:21.582-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:01:21.585-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:01:21.585-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:01:21.585-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:01:21.585-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:01:21.586-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:01:21.609-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-03-24T06:01:52.657-0300] {processor.py:161} INFO - Started process (PID=43611) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:01:52.658-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:01:52.659-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:01:52.659-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:01:52.662-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:01:52.661-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:01:52.662-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:01:52.662-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:01:52.662-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:01:52.690-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-03-24T06:02:23.072-0300] {processor.py:161} INFO - Started process (PID=43984) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:02:23.072-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:02:23.073-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:02:23.073-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:02:23.076-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:02:23.076-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:02:23.077-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:02:23.076-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:02:23.077-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:02:23.106-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-03-24T06:02:54.281-0300] {processor.py:161} INFO - Started process (PID=44299) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:02:54.282-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:02:54.283-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:02:54.283-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:02:54.287-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:02:54.286-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:02:54.288-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:02:54.288-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:02:54.288-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:02:54.315-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-03-24T06:03:24.673-0300] {processor.py:161} INFO - Started process (PID=44664) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:03:24.674-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:03:24.675-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:03:24.675-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:03:24.678-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:03:24.678-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:03:24.679-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:03:24.679-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:03:24.679-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:03:24.706-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-03-24T06:03:55.159-0300] {processor.py:161} INFO - Started process (PID=44975) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:03:55.160-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:03:55.161-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:03:55.161-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:03:55.163-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:03:55.163-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:03:55.164-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:03:55.164-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:03:55.164-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:03:55.187-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-03-24T06:04:26.155-0300] {processor.py:161} INFO - Started process (PID=45348) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:04:26.156-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:04:26.157-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:04:26.157-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:04:26.161-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:04:26.160-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:04:26.161-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:04:26.161-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:04:26.161-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:04:26.184-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-03-24T06:04:56.745-0300] {processor.py:161} INFO - Started process (PID=45654) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:04:56.747-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:04:56.748-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:04:56.748-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:04:56.750-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:04:56.750-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:04:56.750-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:04:56.750-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:04:56.751-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:04:56.778-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-24T06:05:27.113-0300] {processor.py:161} INFO - Started process (PID=46087) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:05:27.114-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:05:27.115-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:05:27.114-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:05:27.119-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:05:27.118-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:05:27.119-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:05:27.119-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:05:27.119-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:05:27.149-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2024-03-24T06:05:57.977-0300] {processor.py:161} INFO - Started process (PID=46399) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:05:57.978-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:05:57.979-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:05:57.979-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:05:57.983-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:05:57.983-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:05:57.984-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:05:57.984-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:05:57.984-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:05:58.007-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-03-24T06:06:29.142-0300] {processor.py:161} INFO - Started process (PID=46773) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:06:29.143-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:06:29.144-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:06:29.144-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:06:29.147-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:06:29.146-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:06:29.147-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:06:29.147-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:06:29.148-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:06:29.176-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-03-24T06:06:59.243-0300] {processor.py:161} INFO - Started process (PID=47072) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:06:59.244-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:06:59.245-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:06:59.245-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:06:59.247-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:06:59.247-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:06:59.247-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:06:59.247-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:06:59.247-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:06:59.275-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-03-24T06:07:29.449-0300] {processor.py:161} INFO - Started process (PID=47441) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:07:29.450-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:07:29.452-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:07:29.451-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:07:29.455-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:07:29.455-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:07:29.456-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:07:29.456-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:07:29.456-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:07:29.480-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-03-24T06:08:00.227-0300] {processor.py:161} INFO - Started process (PID=47747) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:08:00.228-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:08:00.229-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:08:00.228-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:08:00.231-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:08:00.231-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:08:00.231-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:08:00.231-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:08:00.232-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:08:00.256-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-03-24T06:08:31.050-0300] {processor.py:161} INFO - Started process (PID=48125) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:08:31.052-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:08:31.053-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:08:31.053-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:08:31.058-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:08:31.057-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:08:31.058-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:08:31.058-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:08:31.059-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:08:31.085-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-24T06:09:01.760-0300] {processor.py:161} INFO - Started process (PID=48440) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:09:01.761-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:09:01.762-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:09:01.762-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:09:01.765-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:09:01.765-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:09:01.766-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:09:01.765-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:09:01.766-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:09:01.801-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-03-24T06:09:32.682-0300] {processor.py:161} INFO - Started process (PID=48814) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:09:32.683-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:09:32.684-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:09:32.684-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:09:32.686-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:09:32.686-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:09:32.687-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:09:32.687-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:09:32.687-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:09:32.717-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-24T06:10:03.268-0300] {processor.py:161} INFO - Started process (PID=49120) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:10:03.269-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:10:03.270-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:10:03.269-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:10:03.272-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:10:03.272-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:10:03.272-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:10:03.272-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:10:03.273-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:10:03.303-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-03-24T06:10:33.467-0300] {processor.py:161} INFO - Started process (PID=49550) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:10:33.468-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:10:33.469-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:10:33.468-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:10:33.471-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:10:33.471-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:10:33.472-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:10:33.472-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:10:33.472-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:10:33.501-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-24T06:11:03.708-0300] {processor.py:161} INFO - Started process (PID=49854) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:11:03.709-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:11:03.710-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:11:03.710-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:11:03.716-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:11:03.715-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:11:03.717-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:11:03.717-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:11:03.717-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:11:03.748-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-03-24T06:11:34.051-0300] {processor.py:161} INFO - Started process (PID=50225) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:11:34.053-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:11:34.054-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:11:34.053-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:11:34.057-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:11:34.056-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:11:34.057-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:11:34.057-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:11:34.057-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:11:34.093-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-03-24T06:12:04.326-0300] {processor.py:161} INFO - Started process (PID=50530) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:12:04.327-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:12:04.328-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:12:04.327-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:12:04.330-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:12:04.330-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:12:04.330-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:12:04.330-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:12:04.331-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:12:04.359-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-03-24T06:12:35.465-0300] {processor.py:161} INFO - Started process (PID=50905) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:12:35.468-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:12:35.473-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:12:35.473-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:12:35.476-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:12:35.476-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:12:35.476-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:12:35.476-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:12:35.477-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:12:35.505-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-03-24T06:13:06.063-0300] {processor.py:161} INFO - Started process (PID=51216) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:13:06.064-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:13:06.064-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:13:06.064-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:13:06.067-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:13:06.066-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:13:06.067-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:13:06.067-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:13:06.067-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:13:06.097-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-03-24T06:13:36.389-0300] {processor.py:161} INFO - Started process (PID=51581) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:13:36.391-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:13:36.393-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:13:36.392-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:13:36.396-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:13:36.395-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:13:36.396-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:13:36.396-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:13:36.397-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:13:36.428-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-03-24T06:14:06.646-0300] {processor.py:161} INFO - Started process (PID=51890) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:14:06.647-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:14:06.647-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:14:06.647-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:14:06.650-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:14:06.649-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:14:06.650-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:14:06.650-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:14:06.650-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:14:06.681-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-24T06:14:36.904-0300] {processor.py:161} INFO - Started process (PID=52255) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:14:36.905-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:14:36.906-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:14:36.906-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:14:36.911-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:14:36.910-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:14:36.912-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:14:36.911-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:14:36.912-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:14:36.940-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-24T06:15:07.231-0300] {processor.py:161} INFO - Started process (PID=52576) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:15:07.232-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:15:07.234-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:15:07.233-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:15:07.237-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:15:07.236-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:15:07.238-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:15:07.237-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:15:07.238-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:15:07.269-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-03-24T06:15:37.416-0300] {processor.py:161} INFO - Started process (PID=52994) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:15:37.418-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:15:37.419-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:15:37.419-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:15:37.422-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:15:37.421-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:15:37.422-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:15:37.422-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:15:37.423-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:15:37.451-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-24T06:16:08.009-0300] {processor.py:161} INFO - Started process (PID=53308) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:16:08.010-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:16:08.011-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:16:08.010-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:16:08.017-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:16:08.016-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:16:08.017-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:16:08.017-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:16:08.018-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:16:08.045-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-03-24T06:16:38.173-0300] {processor.py:161} INFO - Started process (PID=53670) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:16:38.174-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:16:38.175-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:16:38.174-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:16:38.177-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:16:38.176-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:16:38.177-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:16:38.177-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:16:38.177-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:16:38.206-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-03-24T06:17:08.551-0300] {processor.py:161} INFO - Started process (PID=54010) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:17:08.552-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:17:08.553-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:17:08.553-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:17:08.556-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:17:08.555-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:17:08.556-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:17:08.556-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:17:08.556-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:17:08.584-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-03-24T06:17:38.919-0300] {processor.py:161} INFO - Started process (PID=54349) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:17:38.920-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:17:38.921-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:17:38.921-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:17:38.924-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:17:38.924-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:17:38.925-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:17:38.925-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:17:38.925-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:17:38.961-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-03-24T06:18:09.045-0300] {processor.py:161} INFO - Started process (PID=54682) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:18:09.047-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:18:09.047-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:18:09.047-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:18:09.050-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:18:09.049-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:18:09.050-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:18:09.050-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:18:09.051-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:18:09.081-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-24T06:18:39.263-0300] {processor.py:161} INFO - Started process (PID=55020) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:18:39.264-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:18:39.265-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:18:39.265-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:18:39.268-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:18:39.267-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:18:39.268-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:18:39.268-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:18:39.269-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:18:39.299-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-03-24T06:19:10.347-0300] {processor.py:161} INFO - Started process (PID=55398) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:19:10.349-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:19:10.350-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:19:10.349-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:19:10.352-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:19:10.351-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:19:10.352-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:19:10.352-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:19:10.352-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:19:10.381-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2024-03-24T06:19:41.196-0300] {processor.py:161} INFO - Started process (PID=55710) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:19:41.197-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:19:41.198-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:19:41.198-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:19:41.201-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:19:41.201-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:19:41.202-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:19:41.201-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:19:41.202-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:19:41.231-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2024-03-24T06:20:11.664-0300] {processor.py:161} INFO - Started process (PID=56077) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:20:11.665-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:20:11.666-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:20:11.666-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:20:11.669-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:20:11.668-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:20:11.669-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:20:11.669-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:20:11.669-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:20:11.700-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-03-24T06:20:42.108-0300] {processor.py:161} INFO - Started process (PID=56448) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:20:42.108-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:20:42.109-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:20:42.109-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:20:42.115-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:20:42.114-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:20:42.115-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:20:42.115-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:20:42.115-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:20:42.143-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-24T06:21:12.225-0300] {processor.py:161} INFO - Started process (PID=56810) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:21:12.226-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:21:12.227-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:21:12.226-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:21:12.230-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:21:12.229-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:21:12.230-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:21:12.230-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:21:12.230-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:21:12.256-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-03-24T06:21:42.857-0300] {processor.py:161} INFO - Started process (PID=57380) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:21:42.859-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:21:42.860-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:21:42.859-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:21:42.866-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:21:42.865-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:21:42.867-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:21:42.867-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:21:42.868-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:21:42.918-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2024-03-24T06:22:13.287-0300] {processor.py:161} INFO - Started process (PID=57984) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:22:13.288-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:22:13.289-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:22:13.289-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:22:13.292-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:22:13.291-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:22:13.293-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:22:13.293-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:22:13.293-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:22:13.329-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-03-24T06:22:43.774-0300] {processor.py:161} INFO - Started process (PID=58366) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:22:43.776-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:22:43.777-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:22:43.776-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:22:43.797-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:22:43.796-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:22:43.797-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:22:43.797-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:22:43.798-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:22:43.839-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-03-24T06:23:14.070-0300] {processor.py:161} INFO - Started process (PID=58872) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:23:14.073-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:23:14.074-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:23:14.073-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:23:14.077-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:23:14.076-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:23:14.077-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:23:14.077-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:23:14.077-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:23:14.106-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-03-24T06:23:48.749-0300] {processor.py:161} INFO - Started process (PID=59476) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:23:48.770-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:23:48.774-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:23:48.774-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:23:48.778-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:23:48.778-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:23:48.779-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:23:48.779-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:23:48.779-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:23:49.041-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.295 seconds
[2024-03-24T06:24:19.201-0300] {processor.py:161} INFO - Started process (PID=59981) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:24:19.202-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:24:19.204-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:24:19.203-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:24:19.210-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:24:19.209-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:24:19.211-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:24:19.210-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:24:19.211-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:24:19.254-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2024-03-24T06:24:50.010-0300] {processor.py:161} INFO - Started process (PID=60460) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:24:50.011-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:24:50.012-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:24:50.012-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:24:50.014-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:24:50.014-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:24:50.015-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:24:50.014-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:24:50.015-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:24:50.038-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-03-24T06:25:20.695-0300] {processor.py:161} INFO - Started process (PID=61114) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:25:20.696-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:25:20.696-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:25:20.696-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:25:20.699-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:25:20.699-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:25:20.700-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:25:20.699-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:25:20.700-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:25:20.723-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-03-24T06:25:50.942-0300] {processor.py:161} INFO - Started process (PID=61532) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:25:50.943-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:25:50.945-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:25:50.944-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:25:50.949-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:25:50.948-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:25:50.949-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:25:50.949-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:25:50.950-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:25:50.978-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-24T06:26:21.066-0300] {processor.py:161} INFO - Started process (PID=61933) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:26:21.067-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:26:21.067-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:26:21.067-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:26:21.071-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:26:21.070-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:26:21.072-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:26:21.071-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:26:21.072-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:26:21.099-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-03-24T06:26:51.746-0300] {processor.py:161} INFO - Started process (PID=62422) to work on /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:26:51.748-0300] {processor.py:830} INFO - Processing file /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-03-24T06:26:51.749-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:26:51.749-0300] {dagbag.py:540} INFO - Filling up the DagBag from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:26:51.753-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:26:51.752-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-03-24T06:26:51.754-0300] {logging_mixin.py:188} INFO - [2024-03-24T06:26:51.753-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-03-24T06:26:51.754-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-03-24T06:26:51.783-0300] {processor.py:183} INFO - Processing /home/thiago/tcc_ufrj/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
